### ISSUE TITLE
Offhand is not rendered (1.5.7-pre)

### ISSUE THREAD

**Issue by Omgise** [GTNewHorizons/Backhand#26]
https://github.com/user-attachments/assets/7a0c3b79-7e79-47d4-bb5c-82f37f964f88

**Comment by Lyfts** [comment]
Any steps to reproduce?
Are you using the `Use Inventory Slot` option?

Really any info other than the bare minimum would be helpful.

**Comment by Omgise** [comment]
I did not Use the `Use Inventory Slot` option
I don't know how to duplicate this error. Sorry

**Comment by Omgise** [comment]
This is a list of mods I use
`==================== JAR FILES
+++NotEnoughVerbosity-1.7.10-0.2.jar
+MysteriumLib-1.5.7.jar
+unimixins-all-1.7.10-0.1.17.jar
ADFix-1.0.0.jar
adventurebackpack-1.2.0-GTNH.jar
aether-1.7.10-v1.1.2.3.jar
alreadydecoratingfix-1.0a.jar
alternatecurrent-1.4.2.jar
AlternativeStainedGlass-mc1.7.10-v1.0.3.jar
Anvilability-Forge-1.7.10-1.0.0.jar
AOBD-2.9.2.jar
AOBDOC-1.0.5.jar
AppleCore-3.3.0.jar
appliedenergistics2-rv3-beta-412-GTNH.jar
archaicfix-0.7.4.jar
AsieLib-1.7.10-0.5.0.jar
ATOP-1.7.10-v.1.2.jar
Audino-1.1.1.jar
backhand-1.5.8-pre.jar
BetterAchievements-0.3.0.jar
BetterBurning-1.7.10-0.4.2.jar
BetterHorseHud-1.7.10-1.0.jar
BetterLineBreak-1.7.10(Forge)-1.0.1.jar
BetterStorage-1.7.10-0.13.1.128.jar
BetterTooltipBox-v1.1.2.jar
BiblioCraft[v1.11.7][MC1.7.10].jar
BiblioWoods[BiomesOPlenty][v1.9].jar
biggerpacketsplz-upto1.7.10-1.2.jar
BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar
BrandonsCore-1.7.10-1.0.0.13-GTNH.jar
bugtorch-1.2.13.jar
campfirebackport-1.7.10-1.11.1+nomixin.jar
Careful+Cast+Corrector-2.0.jar
ChatCopier-1.7.10-1.1.1.jar
ChocoCraftPlus-1.7.10-4.5.9.jar
chunkapi-mc1.7.10-0.5.1.jar
CodeChickenCore-1.3.6.jar
Coffee+Spawner-1.7.10-1.0.2.jar
CoFHCore-mc1.7.10-3.1.4-revived.jar
colorfulhealthbar-1.7.10-1.0.0.jar
ColorUtility-1.7.10-1.0.3.jar
CookingForBlockheads-1.3.4-GTNH.jar
CoreTweaks-1.7.10-0.3.3.2+nomixin.jar
crafttweaker-mc1.7.10-3.3.2-mega.jar
custom_motd_no_client-1.0.11.jar
D3Core-1.7.10-1.1.3.jar
defaultworldgenerator-0.3.0.jar
DMod-1.7.10-1.0.3.5+nomixin.jar
Draconic-Evolution-1.3.6-GTNH.jar
DragonMounts-1.1.0.jar
DummyCore-1.19.0.jar
easybreading-1.7.10-2.0.3.jar
EggParticleFix-ASM-1.0.jar
ElephantFix-Forge-1.7.10-1.0.0-mixinless.jar
endercore-0.4.6.jar
EnderIO-2.8.17.jar
enderlicious-1.1.2.jar
EnderStorage-1.6.0.jar
endlessids-mc1.7.10-1.5.2.jar
entityculling-1.6.4-mc1.7.10.jar
EntityRenderDistanceExtender-1.0c.jar
etfuturum-2.6.0-master.37+6e423f8d6c.jar
ExtrabiomesXL-3.16.8.jar
ExtraUtilities-1.2.12.2.jar
falsepatternlib-mc1.7.10-1.4.0.jar
falsetweaks-mc1.7.10-3.1.0.jar
FastLeafDecay-1.7.10-1.4.jar
fedropfix-1.0.0.jar
flickerfix-1.7.10-v5.0.0.jar
floatingitems-1.0.jar
FlyingCullers-1.7.10-1.3.jar
geckolib-unofficial-1.7.10-1.0.3.jar
glassbreaker-1.0.0.jar
GlobalGameRules-1.0.jar
GolemTweaks-1.7.10-1.3.3.jar
GreenThumb-1.7.10-1.1.0.8.jar
gregcaves-1.2.1.jar
growthcraft-1.7.10-2.7.3-complete.jar
gtnhlib-0.3.3.jar
Hammerz-1.7.10-0.1.7.37.jar
HardcoreEnderExpansion-1.11.0-GTNH.jar
harvestcraft-1.1.10-GTNH.jar
Healer-1.2.1.jar
HelpFixer-1.3.0.jar
hodgepodge-2.5.38.jar
HorizontalBackport-mc1.7.10-v1.0.0.jar
immersive-snow-1.7.10-1.0b.jar
ImmersiveEngineering-mc1.7.10-0.7.11.jar
immersiveintegration-0.6.8.jar
industrialcraft-2-2.2.828a-experimental.jar
IngameIME-1.7.10-2.0.10.jar
InputFix-1.7.10-v6.jar
inventorytweaks-1.6.2.jar
IronChest-6.0.85.jar
JABBA-1.4.6.jar
JarFinder.jar
KeyboardWizard-Legacy-Forge-1.7.10-1.0.0.jar
kingdomregions-5.6.jar
Lachryvision-1.2.1.jar
legacyfixes-1.8.1.jar
liteloader-1.7.10.jar
lumi-mc1.7.10-1.0.0.jar
Mantle-0.4.1.jar
matmos-1.7.10-36.0.1+nomixin.jar
Mekanism-Community-Edition-1.7.10-9.10.36-ALL.jar
Metallurgy-1.7.10-4.0.9.148.jar
MetallurgyCore-1.7.10-4.0.5.30.jar
MineFactoryReloaded-2.8.1-pilz2.jar
MineTweakerRecipeMaker-1.7.10-1.1.1.jar
mobspawningfix-1.0a.jar
MoCreatures-Legacy-Final-1.1.jar
ModernKeyBinding-Forge-1.7.10-2.1.0-mixinless.jar
modernsplash-1.7.10-1.2.1-d88da6a.dirty.jar
ModTweaker2-0.11.0.jar
MoreEnchantments-1.7.10-1.3.2.1.jar
MoreFurnaces-1.3.9-MC1.7.10.jar
MouseTweaks-2.4.17-GTNH.jar
MrCrayfish'sFurniture-3.4.8.jar
Natura-2.6.5-pre.jar
NaturalAbsorption-1.2.1.1.jar
naturescompass-1.4.3-GTNH.jar
Neat-1.0.3.jar
necrotempus-1.3.2.jar
neodymium-mc1.7.10-0.3.3-unofficial.jar
netherlicious-3.2.8.jar
netherportalfix-1.3.0.jar
Neutron-Forge-1.7.10-0.1.1-hotfix.jar
NGE-1.7.10-1.2.8-forge.jar
NoMoreRecipeConflict-1.7.10-0.3.2.jar
NotEnoughItems-2.6.19-GTNH.jar
NotEnoughPets-1.7.10-2.3.6.jar
notfine-4036351.jar
omniconfig-1.0.1-mc1.7.10.jar
OreExcavation-1.1.134.jar
overloadedarmorbar-1.1.0.jar
PatPatPat-Forge-1.7.10-1.0.0.jar
PineapplePsychic-1.7.jar
PineappleTag-1.5.jar
QuickTrashCan-1.7.10-1.0.0.jar
RandomRandomness-2.0.0.jar
RandomThings-mc1.7.10-2.4.5.jar
rawinput-1.7.10-v1.4.2.jar
ReducedMusicDelay-1.7.10.jar
SafeKeyString-Forge-1.7.10-1.0.0-mixinless.jar
Satchels-1.7.10-1.0.7.jar
serializationisbad-1.5.2.jar
ShoulderSurfing-1.7.10-2.4.1.jar
skinport-v11.0.0.jar
SmoothFont-1.7.10-1.15.3.jar
soundphysics-1.1.1.jar
squidless-1.7.10-0.6.1.jar
Statues-1.7.10-2.2.0.jar
TheFramework-KAMKEEL-v1.jar
ThermalExpansion-[1.7.10]4.1.5-248.jar
ThermalFoundation-[1.7.10]1.2.6-118.jar
TileEntityResetFix-1.0.1-noreq.jar
torohealth-1.1.0.jar
Translocator-1.2.1.jar
TwilightForest-2.6.31.jar
VendingMachinesRevamped_1.1.0_1.7.10.jar
VillageNames-1.7.10-4.4.11.jar
VillagerMetaFix-0.4.jar
vineclimber-3.0.0.jar
Waila-1.8.1.jar
Wawla-1.3.0-GTNH.jar
waystones-1.7.10-v1.0.1a-LE.jar
weaponmod-forge-1.7.10-1.22.0.jar
WheatfieldWithWolf-1.7.10-Day-4.jar
whitelistfixer-mc1.7.10-1.0.0.jar
wild_netherwart-1.7.10-v2.1.jar
Windows Keyboard Fixes-forge-1.7-1.0.1.jar
WirelessCraftingTerminal-1.11.2.jar
WorldSelectionAdvanced-1.7.10-8.jar
Ztones-2.3.1-GTNH.jar
zume-1.1.1.jar
[1.6.4-1.12.2]HighDPI-Fix-1.3.0.jar
[1.7.10]ArmorStatusHUD-client-1.28.jar
[1.7.10]bspkrsCore-universal-6.16.jar
[1.7.10]ForgeCreeperHeal-1.1.1.jar
1.7.10\BaublesExpanded-2.1.4.jar
1.7.10\CodeChickenLib-1.3.0.jar
1.7.10\ForgeMultipart-1.5.0.jar
ic2\EJML-core-0.26.jar

==================== OTHER FILES
PresenceFootsteps_r5c_Unofficial__1.7.10.litemod
presencefootsteps\userconfig.cfg`

**Comment by Lyfts** [comment]
I spy MysteriumLib, it wouldn't shock me if whatever cursed mod is using that is overwriting the first person render.

But to be sure can you send fml-client-latest from the logs folder?

**Comment by Omgise** [comment]
[fml-client-latest.log](https://github.com/user-attachments/files/16483233/fml-client-latest.log)

**Comment by Omgise** [comment]
@Lyfts I found out that the Aether mod was causing the problem, using an initial first person rendering

**Comment by brandyyn** [comment]
> @Lyfts I found out that the Aether mod was causing the problem, the rendering is normal after removing it. ![image](https://private-user-images.githubusercontent.com/106000018/356558344-b15dce0d-8cbd-4d18-af6e-9837d0905abf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDA5MTYsIm5iZiI6MTczMzM0MDYxNiwicGF0aCI6Ii8xMDYwMDAwMTgvMzU2NTU4MzQ0LWIxNWRjZTBkLThjYmQtNGQxOC1hZjZlLTk4MzdkMDkwNWFiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxOTMwMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzNjMTZlOWY5MzdmYzkzOTdhM2NlY2RlNzBmZDRjOWY2YWQyM2FlMDYyYWRkNTk1YTFmZjlkZjUxOGYyMDBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KLik0YYsZjWs5ZxcOyBkkrr8qa9FaVSeGsUl5MBTXXo)

i added a fix to aether legacy departure if you use that.

**Comment by Lyfts** [comment]
Can you check if this still happens in https://github.com/GTNewHorizons/Backhand/releases/tag/1.6.4?

**Comment by Omgise** [comment]
> Can you check if this still happens in https://github.com/GTNewHorizons/Backhand/releases/tag/1.6.4?

Yes

**Comment by brandyyn** [comment]
> This is still an issue in the current version of Backhand; Aether Legacy prevents the offhand item from rendering in first person.

I fixed it in aether legacy departure, use the cfg option in that

**Comment by FlitPix** [comment]
Sorry but this is still an issue with The Aether v1.1.2.5.

> I fixed it in aether legacy departure, use the cfg option in that

Where is this fork and how can I download it? It seems the only way I've been able to find is to build from source, which isn't something I can just tell people to do in order to play on a server.
