### ISSUE TITLE
Test #46 (1.6.1-pre)

### ISSUE THREAD

**Issue by Darek505** [GTNewHorizons/Backhand#47]
### Your GTNH Discord Username

darek505

### Mod Version

1.6.1-pre

#### Happens only in creative, on the "Survival Inventory" tab

https://github.com/user-attachments/assets/50f1814d-25e7-4869-9754-982059554675

#### When you press the middle mouse button, a phantom block will appear in the copy slot, and a real one will appear next to it.

https://github.com/user-attachments/assets/0256ae0b-2845-4f1b-a0de-efc293a32d2a

#### Totem of undying does not work

https://github.com/user-attachments/assets/a8d43cc2-2e94-431e-b56f-ef8a9f5ade2f

#### Bow does not use arrow from offhand as a high priority

https://github.com/user-attachments/assets/42d75547-f34e-4f7a-8c36-ab86abf3f244

### Java Version

Java 8

### Mod List or GTNH Pack Version

+unimixins-all-1.7.10-0.1.19
backhand-1.6.1-pre
CodeChickenCore-1.4.0
etfuturum-2.6.2
NotEnoughItems-2.7.14-GTNH-pre

### Final Checklist

- [x] I have searched the issues and haven't found a similar issue.

**Comment by Lyfts** [comment]
All of this should be fixed in https://github.com/GTNewHorizons/Backhand/releases/tag/1.6.2-pre

**Comment by Darek505** [comment]
1.6.2-pre: the only thing that still doesn't work is totem of undying:







https://github.com/user-attachments/assets/a2615121-81aa-4151-b148-9d9ff8611d18

Otherwise everything works, thanks
